### ISSUE TITLE
Heatmap label too small

### ISSUE THREAD

**Issue by schwannden** [metaOmic/MetaDE#1]
The heat map displaying label on the top edge of the heat map is really not clear. 
Since different labels have already been separated by the dash line, can you modify the label display such that each group's label is displayed just once?
Instead of:
![1](https://cloud.githubusercontent.com/assets/5753086/18102386/68838dce-6ec0-11e6-881e-bda24dddffbf.png)
Display it as something like this:
![2](https://cloud.githubusercontent.com/assets/5753086/18102365/5c688800-6ec0-11e6-80cf-d255c05d931b.png)

**Comment by Caleb-Huo** [comment]
Same issue.
Another enhancement is to change the study name (Dataset 1) to be the actually study name.
