### ISSUE TITLE
Heat Map FDR Cutoff and image size

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmic/MetaDE#11]
It might be better to have a confirm button.
Otherwise, if I want to input FDR cutoff 0.15, when 0.1 was typed in, the plot will be updated immediately.

**Comment by schwannden** [comment]
Yes I am working on this. I didn't design the button because the plotting is pretty fast. I need a way to delay my action, say, within 1.5 second, if the value didn't change, I'll plot the graph. If I can't make a better UX experience I will use the button.

**Comment by schwannden** [comment]
Because we want the user to quickly see how many genes are left after cutoff before they decided to plot the heat map, lets add the plot button

**Comment by schwannden** [comment]
issue moved to MetaOmics: https://github.com/metaOmic/metaOmics/issues/28
