### ISSUE TITLE
Can not run summary on AW Fisher's result

### ISSUE THREAD

**Issue by schwannden** [metaOmic/MetaDE#2]
When Getting AW Fisher's result from MetaDE, we can't run summary.meta on it

```
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 5133, 0
```

We need to run posthoc.aw first, and run summary.meta on the result of postdoc.aw result. In our Shiny application I can do these steps manually, but do you think user of your package will know that in R console?

**Comment by matianzhou** [comment]
I already fixed this in the 2.2.1 version, now it can deal with both.
