### ISSUE TITLE
Parameter Question

### ISSUE THREAD

**Issue by schwannden** [metaOmic/MetaDE#3]
1. I forgot about parametric option
   - Under what meta method can parametric only be set to TRUE?
   - Under what meta method can parametric only be set to FALSE?
   - Under what meta method can parametric be set to either TRUE or FALSE. In that case, what's the default?
2. Is asymptotic a value for each individual study? And is it only applicable for parsons, spearman, and survival? Also, in the name mapping excel file there's no survival option for individual study. What is the corresponding "label" and "value" for survival? 
3. Is ref.level the label for control group? And what is the name oppose to control group (i.e reference group), is it experiment group?
4. For covariate, rth, select.group , ref.level, and REM.type, could you set the default value to NULL? First of all it is kind of odd that the user need to set a value (even to NULL) for a parameter he is not using. Also I am using a list object as parameters to call MetaDE function, and a list object can not be assigned NULL. So could you help me set the default value of all optional parameter to NULL?

**Comment by matianzhou** [comment]
1. 
   parametric = F only for:
   (a) "Fisher.OC", "SR","PR","minMCC","FEM","REM","rankProd"
   parametric = T/F (basically all other methods can to be set to be TRUE or FALSE):
   (b) "maxP","maxP.OC","minP","minP.OC","Fisher","AW","roP","roP.OC","Stouffer","Stouffer.OC";
   In that case, all category (b) methods, we use parametric = T as default. 
2. 
   asymptotic is a value for each individual study if resp.type="continuous" or "survival"; in other words, only available for pearsonr, spearmanr and survival. So for other methods, the default can be set to be NULL. The labels for survival are just the two column names from the clinical data (one for survival time, the other for the censoring status, the user can specify the two column names in the argument "response", by default, I will assume the first column is survival time and the second is censoring status).
   I will include an example for survival response FYI in the next version.
3. 
   Yes, ref.level is just the reference group, as we discussed before, we did not need users to specify an experimental group (yes, you are correct, the opposed name as to control group can be called experimental group). They just need to select the two groups by using select.group option, and specify the ref.level.

4.
Yes, I will set all default values of advanced options to NULL in the next version.

**Comment by matianzhou** [comment]
The names for REM.type:

HS: Hunter-Schmidt;
HO: Hedges-Olkin;
DL: DerSimonian-Laird;
SJ: Sidik-Jonkman;
EB: Empirical Bayes;
RML: Restricted Maximum Likelihood.

**Comment by schwannden** [comment]
@matianzhou  One more question:
So asymptotic can be set for **individual study** when the **response type** is continuous or survival. Then what does spearmanr and pearsonr has to do with this? Because they belongs to options in **single study method**? Does this mean when our single study method is parsons or spearmanr, we can only have response type set to continuous? Or the other way around?

**Comment by schwannden** [comment]
A list of "dependent parameters" that should be set to NULL as default.
covariate, rth, select.group , ref.level, ind.method, and REM.type

There aren't necessary "advanced option", like "rth" is actually a required option, but dependent on the choice of meta.method. All dependent option should have default value so to not confuse user.

**Comment by matianzhou** [comment]
Yes, when single study method is pearsonr or spearmanr, response type has to be continuous, and vice versa. I have a check function to check this matching.

Sorry, I did not make this clear, I already set all arguments other than the required input to be NULL, including rth, REM.type, etc.

**Comment by schwannden** [comment]
@matianzhou thx for the explanation. You said you already set all arguments other than the required input to be NULL, maybe you forgot to push to github? Because I'm still looking at the old version

**Comment by matianzhou** [comment]
I am working on it now and will push to github soon.

**Comment by matianzhou** [comment]
Sorry, "FEM" and "REM" can also have both parametric =T/F . I already corrected that in my most updated package, this is just FYI.

**Comment by schwannden** [comment]
Clear!
