### ISSUE TITLE
For multi-class comparison, no maxP method is available

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmic/MetaDE#7]
1, For multi-class comparison, maxP method is suggested by the messager.
However, there are only Fisher and AW-Fisher option.

2, There are two label options (Group label and Control label). Do we need both of them? Or only Group label option

3, in advanced option, what is Use complete options?

**Comment by schwannden** [comment]
1. If you click yes in advanced option (in your question 3), you will see all other p-value option. Like maxP, rOP, etc.
2. @xiaoguang1988 Yes we do.

So @matianzhou we'll discuss with George about adding a notification message for using naxP when multi-class comparison is used?

**Comment by schwannden** [comment]
issue moved to metaOmics:
https://github.com/metaOmic/metaOmics/issues/29
