### ISSUE TITLE
Combine p value method

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmic/MetaDE#8]
Only Fisher and AW Fisher are available at this moment.
In the future there will be roP, maxP, minP, Stouffer??

**Comment by matianzhou** [comment]
No worries, all methods are already available in MetaDE. But Fisher and AW-Fisher are the two major methods users will first come up with, others will be the 3rd option (Sorry, I did not have a chance to look at Anche's most recent interface), users can still choose other methods.
